### ISSUE TITLE
tested with my account, does not find password even though its in list

### ISSUE THREAD

**Issue by sw1pe** [originalabhay/haxtagram#1]
it works exactly like the one you said you fixed.

**Comment by Pouriyahe** [comment]
yes it's the samething.
IP is blocked

**Comment by liln1pps** [comment]
is anyone ever going to fix this or continue to post their own 'better' versions that seem to have the same issues? its not as though i could do better but why bother if not following through on providing fixes or answers for consistently mentioned issues?

**Comment by stackerofwheat** [comment]
every single insta brute force on this site is a scam. DO NOT waste any time with instashell, instainsane, or haxtagram. All they do is rapidly spit out your wordlist so you think something is being checked when in reality i doubt these scripts are even connected to the internet after the first 10 or so attempts. The people who post them know that people will check against their own accounts but they also know people will place their password at the beginning of the list - ie BEFORE instagram locks them out. I guarantee you if you put your password in a random spot in a long wordlist it will not be detected. Total scam.

**Comment by originalabhay** [comment]
> every single insta brute force on this site is a scam. DO NOT waste any time with instashell, instainsane, or haxtagram. All they do is rapidly spit out your wordlist so you think something is being checked when in reality i doubt these scripts are even connected to the internet after the first 10 or so attempts. The people who post them know that people will check against their own accounts but they also know people will place their password at the beginning of the list - ie BEFORE instagram locks them out. I guarantee you if you put your password in a random spot in a long wordlist it will not be detected. Total scam.

see that's what the problem is with the noobs! hacking isn't that easy as it looks! i already told to read bloop.lst with your possible passwords! haxtagram works on bruteforce method (attempting passwords one by one)
you must edit bloop.lst with your own guess passwords

**Comment by originalabhay** [comment]
> yes it's the samething.
> IP is blocked

mine is working perfetly! i don't understand the problem

**Comment by originalabhay** [comment]
> it works exactly like the one you said you fixed.

**Comment by originalabhay** [comment]
**SUGGESTION**
_**put your password on bloop.lst file and then try again it will work**_

Brute-Force is different thing it attempts password , there are no tools in this whole world that will give you access to password without doing anything

**Comment by stackerofwheat** [comment]
> > every single insta brute force on this site is a scam. DO NOT waste any time with instashell, instainsane, or haxtagram. All they do is rapidly spit out your wordlist so you think something is being checked when in reality i doubt these scripts are even connected to the internet after the first 10 or so attempts. The people who post them know that people will check against their own accounts but they also know people will place their password at the beginning of the list - ie BEFORE instagram locks them out. I guarantee you if you put your password in a random spot in a long wordlist it will not be detected. Total scam.
> 
> Before telling total scam try harder! Put again your password. see that's what the problem is with the noobs! hacking isn't that easy as it looks! i already told to redit bloop.lst with your possible passwords! haxtagram works on bruteforce method (attempting passwords one by one)
> you must edit bloop.lst with your own guess passwords!

I have no idea what you're talking about. You're telling me to add my password to the wordlist when I think it's pretty clear from my comment that I tried checking my own account against a wordlist containing my actual password and it DID NOT detect it. How much clearer can I be??

**Comment by stackerofwheat** [comment]
One more thing - there are MULTIPLE people who have very clearly commented here that they tried testing their own accounts against their own password and it didn't work and your response to each of them was to "add their password to the wordlist". You seem to think people are complaining because they were expecting a program where you just type in any username and it spits out their password. That's not the case. Everybody here has been using the program as you have designed it and it simply does not work.
